version: "3"
services:
  web:
    build:
      context: .
    ports:
      - 80:5001
    volumes:
      - .:/usr/src/app
  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    ports:
      - "7900:7900"
      - "5900:5900"
      - "4444:4444"
    shm_size: 2g